# Staging environment overrides
environment: Staging
postgres:
  enabled: true
  storage: 5Gi
authService:
  replicas: 2
expenseService:
  replicas: 2
ingress:
  ignoreHealthCheck: false
  host: staging.spendwise.local
secrets:
  existingSecretName: spendwise-secrets
  create: false
