apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spendwise
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - env: dev
            namespace: spendwise-dev
            valuesFile: values-dev.yaml
          - env: staging
            namespace: spendwise-staging
            valuesFile: values-staging.yaml
          - env: prod
            namespace: spendwise-prod
            valuesFile: values-prod.yaml
  template:
    metadata:
      name: 'spendwise-{{ .env }}'
    spec:
      project: spendwise
      source:
        repoURL: https://github.com/ravin00/ExpenseTracker.git
        targetRevision: main
        path: infra/k8s/charts/spendwise
        helm:
          valueFiles:
            - values.yaml
            - '{{ .valuesFile }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PrunePropagationPolicy=foreground
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
  templatePatch: |
    {{- if ne .env "prod" }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
    {{- end }}
