apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spendwise-staging
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - env: staging
            namespace: spendwise-staging
            valuesFile: values-staging.yaml
  template:
    metadata:
      name: 'spendwise-{{ .env }}'
    spec:
      project: spendwise
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /status
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - /status
            - /spec/persistentVolumeClaimRetentionPolicy
          jqPathExpressions:
            - .spec.volumeClaimTemplates[]?.apiVersion
            - .spec.volumeClaimTemplates[]?.kind
            - .spec.volumeClaimTemplates[]?.status
        - group: networking.k8s.io
          kind: Ingress
          jsonPointers:
            - /status
      source:
        repoURL: https://github.com/ravin00/ExpenseTracker.git
        targetRevision: main
        path: infra/k8s/charts/spendwise
        helm:
          valueFiles:
            - values.yaml
            - '{{ .valuesFile }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PrunePropagationPolicy=foreground
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
